# Generated by Django 3.2.4 on 2021-07-08 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de la categoria ')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria ')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de noticia ')),
                ('nombreNotica', models.CharField(max_length=50, verbose_name='Nombre de la noticia ')),
                ('descripcionNoticia', models.CharField(max_length=50, verbose_name='Nombre de la noticia ')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
