# Generated by Django 3.2.4 on 2021-07-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcionNoticia',
            field=models.CharField(max_length=200, verbose_name='descripcion de la noticia '),
        ),
    ]
