# Generated by Django 3.2.4 on 2021-07-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticia_descripcionnoticia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='nombreNotica',
            new_name='nombreNoticia',
        ),
    ]
