# Generated by Django 3.2.4 on 2021-07-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_noticia_imagennoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de usuario ')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre de Usuario ')),
                ('contrasenaUsuario', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
